### ISSUE TITLE
"File "/usr/lib/cups/filter/foomatic-rip-hplip" not available: No such file or directory"

### ISSUE THREAD

**Issue by Georges760** [FranciscoBorges/openwrt-printing-packages#5]
Hi,
I compiled and did everything as you said :
on AA, with only compile of your printer feed, then scp to target, but at the end, I had to install ipks with many manual "opkg install" because adding the local repo in /etc/opkg.conf didn't work for me : it looks for the Packages.gz and I copied by scp only the many ipk files. So this issue may be related to this manual install...
For exemple, Cups web interface didn't works as it, all /usr/shared/doc/cups files where missing, so I had to make another manual scp...

So coming back to this ticket issue : when trying to launch a print with on-target lp command (a png file), the printer give me this error :
"File "/usr/lib/cups/filter/foomatic-rip-hplip" not available: No such file or directory"
and of course this file is missing in the filesystem. On my Ubuntu host there is a symlink : /usr/lib/cups/filter/foomatic-rip -> /usr/bin/foomatic-rip
But the one wanted by target here seems to be related to hplip. I found this is due to the ppd file I use for my printer (HP Deskjet 5600), I extracted if from the hplip 3.13.7 source code (latest).

So I installed hplip 3.9.12 from openwrt online feed (didn't compile it) : http://downloads.openwrt.org/attitude_adjustment/12.09/ar71xx/generic/packages/hplip_3.9.12-4_ar71xx.ipk. After installation, I used the ppd file from this version of hplip. But still not any cups filter (foomatic-rip-hplip or hpcups) in file system...
Even if in /etc/hp/hplip.conf, there is compile option : 
foomatic-drv-install=no
foomatic-ppd-install=no
foomatic-rip-hplip-install=no
hpcups-install=yes

and opkg files hplip give me :
Package hplip (3.9.12-4) is installed on root and has the following files:
/usr/lib/sane/libsane-hpaio.so
/usr/lib/libhpip.so.0
/usr/lib/libhpip.so.0.0.1
/etc/sane.d/dll.d/hplib
/usr/lib/cups/backend/hp
/usr/lib/sane/libsane-hpaio.so.1.0.0
/etc/hotplug.d/usb/20-hplip
/etc/hp/hplip.conf
/usr/share/hplip/data/models/models.dat
/usr/lib/libhpmud.so.0.0.6
/usr/lib/libhpip.so
/usr/lib/sane/libsane-hpaio.so.1
/usr/lib/libhpmud.so
/usr/lib/libhpmud.so.0

I am a little bit lost. Maybe when adding the printer, I should not select the one found by cups usb backend, but the generic HPLIP one ? But have to give the access manually... And which ppd file sould I use ?

Maybe I should try to port latest version of hplip 3.13.7 as it is relative to cups 1.5, that you use here... If I do so, I will put it on github so you can add it to into your already very good printing feed.

**Comment by gsustek** [comment]
Hi , could you please send instructions?
